require("messages").setup()
require("substitute").setup({})
require("nvim-surround").setup({})
require("package-info").setup({ autostart = false })
require("allegro-metrum").setup({})
require("tsc").setup({})
require("bqf").setup({})
require("lsp-file-operations").setup({})
vim.cmd("let g:cursorword_disable_filetypes = ['fugitive', 'NvimTree']")
vim.cmd("let g:cursorword_disable_at_startup = v:false")

require("mini.ai").setup()
require("clear-action").setup({ signs = { enable = false } })
require("textcase").setup({})
