-- local tint = safe_require("tint")

-- if not tint then
-- 	return
-- end

-- tint.setup({
-- 	window_ignore_function = function(winid)
-- 		local bufid = vim.api.nvim_win_get_buf(winid)
-- 		local isFloating = vim.api.nvim_win_get_config(winid).relative ~= ""
-- 		local ignoredFiletypes = { "DiffviewFiles", "DiffviewFileHistory" }
-- 		local ignoredBuftypes = { "terminal" }
-- 		local isDiff = vim.api.nvim_win_get_option(winid, "diff")
--
-- 		local isIgnoredBuftype = vim.tbl_contains(ignoredBuftypes, vim.api.nvim_buf_get_option(bufid, "buftype"))
-- 		local isIgnoredFiletype = vim.tbl_contains(ignoredFiletypes, vim.api.nvim_buf_get_option(bufid, "filetype"))
--
-- 		if isDiff or isFloating or isIgnoredBuftype or isIgnoredFiletype then
-- 			require("tint").untint(winid)
-- 		end
--
-- 		return isDiff or isFloating or isIgnoredBuftype or isIgnoredFiletype
-- 	end,
-- })
