require("utils.module_utils")

reload("dupa.colorscheme")
reload("dupa.options")
reload("dupa.mappings")
reload("dupa.which-key")

require("dupa.packer-plugins")
require("dupa.treesitter")
require("dupa.nvim-tree")
require("dupa.lualine")
require("dupa.telescope")
require("dupa.cmp")
require("dupa.autopairs")
require("dupa.impatient")
require("dupa.alpha")
require("dupa.comment")
require("dupa.lastplace")
require("dupa.lsp")
require("dupa.dressing")
reload("dupa.toggleterm")
require("dupa.lsp-saga")
require("dupa.auto-save")
require("dupa.tint")
require("dupa.spectre")
require("dupa.git")
require("dupa.other")
require("dupa.neotest")
require("dupa.dap")
require("dupa.tint")
require("config.luasnip")
require("dupa.auto-session")
require("dupa.null-ls")
require("dupa.hydra")
require("dupa.haskell")
require("dupa.ufo")
require("dupa.stickybuf")
require("dupa.aerial")
reload("dupa.noice")
require("dupa.other_plugins")

vim.api.nvim_create_user_command("ReloadConfig", function()
	reload("init")
	vim.notify("Reloaded whole config")
end, {})
