-- local copilot = require("copilot")
-- local copilot_suggestion = require("copilot.suggestion")
--
-- copilot.setup({
--   suggestion = {
--     enabled = true,
--     auto_trigger = true,
--     debounce = 500,
--     keymap = {
--       accept = nil,
--       accept_word = false,
--       accept_line = false,
--       next = nil,
--       prev = nil,
--       dismiss = "<C-]>",
--     },
--   },
-- })
--
-- local keymap_amend = require("keymap-amend")
--
-- keymap_amend("i", "<Right>", function(original)
--   if copilot_suggestion.is_visible() then
--     copilot_suggestion.accept()
--   else
--     original()
--   end
-- end)
--
-- keymap_amend("i", "<C-,>", function(original)
--   if copilot_suggestion.is_visible() then
--     copilot_suggestion.next()
--   else
--     original()
--   end
-- end)
--
--
